# Generated by Django 5.1.1 on 2024-09-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_ai',
            field=models.BooleanField(default=False),
        ),
    ]
