# Generated by Django 5.1.1 on 2024-09-16 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'managed': True, 'ordering': ['game_date']},
        ),
        migrations.AlterModelOptions(
            name='waitroom',
            options={'managed': True},
        ),
        migrations.AlterUniqueTogether(
            name='tourparticipation',
            unique_together={('userid', 'tournament')},
        ),
        migrations.AlterModelTable(
            name='match',
            table='match',
        ),
        migrations.AlterModelTable(
            name='waitroom',
            table='waitroom',
        ),
    ]
