# Generated by Django 5.1 on 2024-08-22 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetourn', models.DateTimeField()),
                ('hexblock', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tournament',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('intra', models.BooleanField()),
                ('campus', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('lastname', models.CharField(blank=True, max_length=140, null=True)),
                ('img', models.CharField(max_length=300)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datamatch', models.DateTimeField()),
                ('score', models.CharField(blank=True, max_length=5, null=True)),
                ('tournamentid', models.ForeignKey(db_column='tournamentid', on_delete=django.db.models.deletion.DO_NOTHING, to='app.tournament')),
                ('usersid1', models.ForeignKey(db_column='usersid1', on_delete=django.db.models.deletion.DO_NOTHING, related_name='match_as_user1', to='app.users')),
                ('usersid2', models.ForeignKey(blank=True, db_column='usersid2', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match_as_user2', to='app.users')),
            ],
            options={
                'db_table': 'match',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.users')),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'userstatus',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tourparticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournamentid', models.ForeignKey(db_column='tournamentid', on_delete=django.db.models.deletion.DO_NOTHING, to='app.tournament')),
                ('usersid', models.ForeignKey(db_column='usersid', on_delete=django.db.models.deletion.DO_NOTHING, to='app.users')),
            ],
            options={
                'db_table': 'tourparticipation',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='winnerid',
            field=models.ForeignKey(blank=True, db_column='winnerid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.users'),
        ),
        migrations.CreateModel(
            name='Matchhistorty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchid', models.ForeignKey(db_column='matchid', on_delete=django.db.models.deletion.DO_NOTHING, to='app.match')),
                ('usersid', models.ForeignKey(db_column='usersid', on_delete=django.db.models.deletion.DO_NOTHING, to='app.users')),
            ],
            options={
                'db_table': 'matchhistorty',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pending', models.BooleanField(default=True)),
                ('usersid1', models.ForeignKey(db_column='usersid1', on_delete=django.db.models.deletion.CASCADE, related_name='friends_as_user1', to='app.users')),
                ('usersid2', models.ForeignKey(db_column='usersid2', on_delete=django.db.models.deletion.CASCADE, related_name='friends_as_user2', to='app.users')),
            ],
            options={
                'db_table': 'friends',
                'managed': True,
                'unique_together': {('usersid1', 'usersid2')},
            },
        ),
    ]
