# Generated by Django 5.1.1 on 2024-09-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_users_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='intra_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
