# Generated by Django 5.1.1 on 2024-09-23 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_users_is_ai'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='waitroom',
            unique_together=set(),
        ),
    ]
