# Generated by Django 5.1.1 on 2024-09-23 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_waitroom_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitroom',
            name='attendee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attending_room', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='waitroom',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_room', to=settings.AUTH_USER_MODEL),
        ),
    ]
