# Generated by Django 5.1.1 on 2024-09-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_waitroom_attendee_alter_waitroom_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitroom',
            name='genId',
            field=models.CharField(editable=False, max_length=36, unique=True),
        ),
    ]
