# Generated by Django 5.1.1 on 2024-09-27 15:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_waitroom_genid'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='game_id',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=36, unique=True),
            preserve_default=False,
        ),
    ]
