# Generated by Django 5.1.1 on 2024-09-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_match_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='game_id',
            field=models.CharField(editable=False, max_length=36),
        ),
    ]
